# Generated by Django 4.1.1 on 2023-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media')),
                ('music_lyrics', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
