# Generated by Django 4.1.1 on 2023-06-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='file',
            field=models.FileField(upload_to='audio'),
        ),
    ]
