# Generated by Django 4.1.1 on 2023-06-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_pages', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='category',
            name='sound',
            field=models.ManyToManyField(to='Main_pages.sound'),
        ),
    ]
