# Generated by Django 4.1.1 on 2023-06-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_pages', '0004_remove_category_products_category_sound'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
