# Generated by Django 4.1.1 on 2023-06-11 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_pages', '0007_alter_sound_file_alter_sound_image'),
        ('User_pages', '0002_myuser_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sounds',
            field=models.ManyToManyField(to='Main_pages.sound'),
        ),
        migrations.CreateModel(
            name='FavoriteMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sounds', models.ManyToManyField(to='Main_pages.sound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
