# Generated by Django 4.1.1 on 2023-06-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_pages', '0003_myuser_sounds_favoritemusic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritemusic',
            old_name='sounds',
            new_name='musics',
        ),
    ]
