# Generated by Django 4.1.1 on 2023-06-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_pages', '0004_rename_sounds_favoritemusic_musics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritemusic',
            name='musics',
        ),
    ]
