# Generated by Django 4.1.1 on 2023-06-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_pages', '0009_myuser_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteMusic',
        ),
    ]
