# Generated by Django 4.1.1 on 2023-06-16 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_pages', '0007_alter_sound_file_alter_sound_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_pages', '0012_playlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allow_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.ManyToManyField(to='Main_pages.sound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
