# Generated by Django 4.1.1 on 2023-06-16 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_pages', '0007_alter_sound_file_alter_sound_image'),
        ('User_pages', '0013_allow_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allow_list',
            new_name='AllowList',
        ),
    ]
